#!/bin/bash
#
# install
#
# eric o meehan
# 2022-05-24
#
# adds this user to a given installation

USER_ID=user-template

function log() {
	priority=${2:-6}
	executable=$(cd $(dirname $0) && pwd)/$0
	[[ $syslogServer != 0 ]] && syslogServerArg="-n $syslogServer --tcp"
	tag="executable={{ $executable }} | executionId={{ $executionId }}"
	logger -p $priority -t "$tag" $syslogServerArg "$1"
}

while [[ $# -gt 0 ]]
do
	case $1 in
		-e|--executionId)
			executionId=$2
			shift ; shift ;;
		-g|--groupId)
			groupId=$2
			shift ; shift ;;
		-i|--installationId)
			installationId=$2
			shift ; shift ;;
		-s|--syslogServer)
			syslogServer=$2
			shift ; shift ;;
		*)
			echo "invalid argument: $1" >&2
			exit 1 ;;
	esac
done
[[ -z $executionId ]] && executionId=$(uuidgen)
[[ -z $groupId ]] && groupId=0
[[ -z $syslogServer ]] && syslogServer=0
if [[ -z $installationId ]]
then
	log "argument required | argument={{ installationId }}" 3
	log "exiting" 3
	exit 1
fi

if [[ -z $groupId ]]
then
	userSource=/usr/local/src/$installationId/users/$userId
else
	userSource=/usr/local/src/$installationId/groups/$groupId/users/$userId
fi

log "begin"
log "installing user | userId={{ $USER_ID }}"

# ...

for policy in $(ls $userSource/policies)
do
	log "installing user policy | policy={{ $policy }}"
	.$userSource/policies/$policy/install		\
		--executionId $executionId		\
		--groupId $groupId			\
		--installationId $installationId	\
		--syslogServer $syslogServer		\
		--userId $USER_ID
done
